// Copyright (c) 2025 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// NOTE: This is a workspace-aware Resource API.
// Please see workspace.v1 for more information.
syntax = "proto3";

package arista.studio_topology.v1;

option go_package = "github.com/aristanetworks/cloudvision-go/api/arista/studio_topology.v1;studio_topology";

import "fmp/extensions.proto";
import "fmp/yang.proto";
import "fmp/wrappers.proto";

import "arista/workspace.v1/workspace.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

option (fmp.disable_yang) = "repeated-key-fields";

// Element defines the fundamental types of elements in topology.
enum Element {
	// ELEMENT_UNSPECIFIED indicates an unspecified element type.
	ELEMENT_UNSPECIFIED = 0;
	// ELEMENT_DEVICE indicates a device.
	ELEMENT_DEVICE = 1;
	// ELEMENT_INTERFACE indicates an interface.
	ELEMENT_INTERFACE = 2;
	// ELEMENT_CONNECTION indicates a connection.
	ELEMENT_CONNECTION = 3;
}

// Operation defines the operations that may be performed on the topology.
enum Operation {
	// OPERATION_UNSPECIFIED indicates an unspecified operation.
	OPERATION_UNSPECIFIED = 0;
	// OPERATION_ADDED indicates addition of an Element.
	OPERATION_ADDED = 1;
	// OPERATION_MODIFIED indicates modification of an Element.
	OPERATION_MODIFIED = 2;
	// OPERATION_REMOVED indicates removal of an Element.
	OPERATION_REMOVED = 3;
}

// UpdateStatus defines the set of statuses that apply to individual topology updates.
enum UpdateStatus {
	// UPDATE_STATUS_UNSPECIFIED indicates an unspecified update status.
	UPDATE_STATUS_UNSPECIFIED = 0;
	// UPDATE_STATUS_NEW indicates the update is new.
	UPDATE_STATUS_NEW = 1;
	// UPDATE_STATUS_ACCEPTED indicates the update is accepted.
	UPDATE_STATUS_ACCEPTED = 2;
	// UPDATE_STATUS_IGNORED indicates the update is ignored.
	UPDATE_STATUS_IGNORED = 3;
}

// DeviceStatus defines the set of statuses that apply to a device.
enum DeviceStatus {
	// DEVICE_STATUS_UNSPECIFIED is the default unspecified device status.
	DEVICE_STATUS_UNSPECIFIED = 0;
	// DEVICE_STATUS_ACTIVE indicates a device is streaming its telemetry data
	// to CloudVision.
	DEVICE_STATUS_ACTIVE = 1;
	// DEVICE_STATUS_INACTIVE indicates a device is not streaming its telemetry data
	// to CloudVision.
	DEVICE_STATUS_INACTIVE = 2;
	// DEVICE_STATUS_EXPECTED indicates a device has not yet streamed its telemetry
	// data to CloudVision.
	DEVICE_STATUS_EXPECTED = 3;
	// DEVICE_STATUS_DECOMMISSIONED indicates a device that has been previously decommissioned.
	DEVICE_STATUS_DECOMMISSIONED = 4;
 }

// DeviceInfo contains device properties.
message DeviceInfo {
	// device_id identifies the device uniquely.
	google.protobuf.StringValue device_id = 1;
	// model_name indicates the model of the device.
	google.protobuf.StringValue model_name = 2;
	// mac_address indicates the MAC address of the device.
	fmp.MACAddress mac_address = 3;
	// hostname indicates the hostname of the device.
	google.protobuf.StringValue hostname = 4;
	// match_any_device is an indicator to match any online device with the device
	// identified by the device_id field above. An online device is any EOS device
	// which is streaming to CVP and has not been provisioned yet.
	// This argument is used only if the device is an expected device and not relevant
	// to other devices.
	// For an expected device, the device_id fields holds an temporary UUID. Hence,
	// the match has to occur based on the combination of expected_serial_numbers
	// and match_any_device fields and not the device_id field.
	// This field is mandatory for an expected device.
	// If this field is true, expected_serial_numbers should be empty.
	// If this field is false, expected_serial_numbers should be provided.
	google.protobuf.BoolValue match_any_device = 5;
	// expected_serial_numbers indicates a list of possible serial numbers which can
	// be expected for this device. The expected device entry specified by the device_id
	// field above will be matched with only one of the serial numbers in this list.
	// Should be populated only for an expected device and when match_any_device is set to false.
	fmp.RepeatedString expected_serial_numbers = 6;
}

// InterfaceInfo contains interface properties.
message InterfaceInfo {
	// name is the name of an interface.
	google.protobuf.StringValue name = 1;
	// neighbor_device_id indicates the device ID of the neighbor to which
	// this interface is connected.
	// For an expected device, this would be a device_id (temporary UUID in case
	// the neighbour is also an expected device) of a known device resource to the
	// studios or lldp sysname in case of a non Arista device like third party
	// external router.
	google.protobuf.StringValue neighbor_device_id = 2;
	// neighbor_interface_name indicates the interface on the neighbor to which
	// this interface is connected.
	// For expected devices having the neighbour as a non Arista device, this field
	// does not need to be populated.
	google.protobuf.StringValue neighbor_interface_name = 3;
	// non_provisioned indicates if the interface is connected to a non-provisioned device, ie, a
	// device which is not part of the I&T studio and cannot be provisioned by CloudVision.
	google.protobuf.BoolValue non_provisioned = 4;
}

// InterfaceInfos is a list of InterfaceInfo.
message InterfaceInfos {
	// values is a list of InterfaceInfo.
	repeated InterfaceInfo values = 1;
}

// DeviceKey uniquely identifies the device for a workspace.
message DeviceKey {
	option (fmp.model_key) = true;
	// workspace_id identifies the workspace uniquely.
	google.protobuf.StringValue workspace_id = 1;
	// device_id identifies the device uniquely.
	google.protobuf.StringValue device_id = 2;
}

// DeviceInputConfig is the desired topology input for a device.
message DeviceInputConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the device ID for a given workspace.
	DeviceKey key = 1;
	// device_info contains device properties.
	DeviceInfo device_info = 2;
	// remove if set to true will remove the device from mainline
	// post workspace merge.
	google.protobuf.BoolValue remove = 3;
	// is_expected_device specifies if this is an expected device.
	google.protobuf.BoolValue is_expected_device = 4;
}

// InterfaceInputKey is the set of inputs that uniquely identify
// the interface for a workspace.
message InterfaceInputKey {
	option (fmp.model_key) = true;
	// workspace_id identifies the workspace uniquely.
	google.protobuf.StringValue workspace_id = 1;
	// device_id identifies the device uniquely.
	google.protobuf.StringValue device_id = 2;
	// interface_id along with device_id identifies the interface uniquely.
	google.protobuf.StringValue interface_id = 3;
}

// InterfaceInputConfig is the resource for manually adding
// an interface in I&T studios.
message InterfaceInputConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the interface for a given workspace.
	InterfaceInputKey key = 1;
	// interface_info contains interface properties.
	InterfaceInfo interface_info = 2;
	// remove if set to true will remove the interface from mainline
	// post workspace merge.
	google.protobuf.BoolValue remove = 3;
}

// DeviceState is the state of a device written by
// InterfaceInputConfig, DeviceInputConfig and
// UpdateConfig resources.
message DeviceState {
	option (fmp.model) = "ro";
	// key uniquely identifies the device for a given workspace.
	DeviceKey key = 1;
	// device_info contains device properties.
	DeviceInfo device_info = 2;
	// interface_infos contains interface properties of all the interfaces
	// belonging to the device.
	InterfaceInfos interface_infos = 3;
	// device_status contains the status of the device.
	DeviceStatus device_status = 4;
}

// UpdateKey uniquely identifies a workspace topology update.
message UpdateKey {
	option (fmp.model_key) = true;
	// workspace_id identifies the workspace uniquely.
	google.protobuf.StringValue workspace_id = 1;
	// update_id identifies the update uniquely.
	google.protobuf.StringValue update_id = 2;
}

// UpdateConfig contains the acceptance status of an Update.
message UpdateConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the update.
	UpdateKey key = 1;
	// status indicates the status of the topology update.
	UpdateStatus status = 2;
	// remove if set to true will remove the update key from mainline
	// post workspace merge. This can only be set true for ignored keys
	// since we don't carry accepted keys to mainline post workspace
	// merge.
	google.protobuf.BoolValue remove = 3;
}

// Update represents an update on to the workspace.
message Update {
	option (fmp.model) = "ro";
	// key uniquely identifies the update.
	UpdateKey key = 1;
	// element indicates the type of a network element.
	Element element = 2;
	// operation indicates the type of operation on the topology update.
	Operation operation = 3;
	// status indicates the status of the topology update.
	UpdateStatus status = 4;
	// description describes the topology update in short.
	google.protobuf.StringValue description = 5;
	// device_id indicates the device associated with the update.
	google.protobuf.StringValue device_id = 6;
}

// UpdateSyncConfig model represents a point in time all updates
// are to be accepted.
message UpdateSyncConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the workspace.
	arista.workspace.v1.WorkspaceKey key = 1;
	// sync_time indicates the desired synchronization time with the live topology.
	// If the sync_time indicated in the config takes effect without error,
	// it will appear in the state model, and then all updates that occurred up to
	// and including the timestamp in the state model will be accepted.
	google.protobuf.Timestamp sync_time = 2;
}

// RevertConfig is the model provided to revert a workspace.
message RevertConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the workspace.
	arista.workspace.v1.WorkspaceKey key = 1;
}

// DecommissionConfig is the resource for decommissioning
// the device from the studio.
message DecommissionConfig {
	option (fmp.model) = "rw";
	// key uniquely identifies the device for a given workspace.
	DeviceKey key = 1;
}

// Decommission is the resource that holds the decommissioning
// state of a device.
message Decommission {
	option (fmp.model) = "ro";
	// key uniquely identifies the device in a given workspace.
	DeviceKey key = 1;
	// created_at is the time at which decommissioning was first initiated.
	google.protobuf.Timestamp created_at = 2;
	// created_by is the name of the user who first initiated decommissioning.
	google.protobuf.StringValue created_by = 3;
	// last_modified_at is the time at which the decommissioning was last modified.
	google.protobuf.Timestamp last_modified_at = 4;
	// last_modified_by is the name of the user that last modified the status.
	google.protobuf.StringValue last_modified_by = 5;
	// status is the status of the decommissioning operation.
	DecommissionStatus status = 6;
	// error indicates if there is a failure in decommissioning.
	google.protobuf.StringValue error = 7;
}

// DecommissionStatus enumerates the status of decommissioning a device.
enum DecommissionStatus {
	// DECOMMISSION_STATUS_UNSPECIFIED indicates that the device was decommissioned with
	// an unspecified state.
	DECOMMISSION_STATUS_UNSPECIFIED = 0;
	// DECOMMISSION_STATUS_SUCCESS indicates that the device was successfully decommissioned.
	DECOMMISSION_STATUS_SUCCESS = 1;
	// DECOMMISSION_STATUS_FAILURE indicates an error with decommissioning the device.
	DECOMMISSION_STATUS_FAILURE = 2;
}

// ReplaceConfig is the resource for replacing a device with another device in Studios.
message ReplaceConfig{
	option (fmp.model) = "rw";
	// key uniquely identifies the original device to be replaced in a given workspace.
	DeviceKey key = 1;
	// replacement_device_id is the device to replace the original device with.
	// All references to the original device in Studios and tags will be replaced with this device.
	google.protobuf.StringValue replacement_device_id = 2;
}

// Replace is the resource that holds the status of the replace operation.
message Replace{
	option (fmp.model) = "ro";
	// key uniquely identifies the original device for a given workspace.
	DeviceKey key = 1;
	// replacement_device_id is the device to replace the original device with.
	google.protobuf.StringValue replacement_device_id = 2;
	// created_at is the time at which the status was first set.
	google.protobuf.Timestamp created_at = 3;
	// created_by is the name of the user that first set the status.
	google.protobuf.StringValue created_by = 4;
	// last_modified_at is the time at which the status was last modified.
	google.protobuf.Timestamp last_modified_at = 5;
	// last_modified_by is the name of the user that last modified the status.
	google.protobuf.StringValue last_modified_by = 6;
	// status indicates the status of the replace operation.
	ReplaceStatus status = 7;
	// error provides the reason if there is a failure in replace.
	google.protobuf.StringValue error = 8;
}

// ReplaceStatus enumerates the status of the device.
enum ReplaceStatus {
	// REPLACE_STATUS_UNSPECIFIED indicates that the device was replaced with
	// an unspecified state.
	REPLACE_STATUS_UNSPECIFIED = 0;
	// REPLACE_STATUS_SUCCESS indicates that the device was successfully replaced.
	REPLACE_STATUS_SUCCESS = 1;
	// REPLACE_STATUS_FAILURE indicates an error with replace.
	REPLACE_STATUS_FAILURE = 2;
}
