// Copyright (c) 2021 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

syntax = "proto3";

package arista.tag.v2;

option go_package = "github.com/aristanetworks/cloudvision-go/api/arista/tag.v2;tag";

import "google/protobuf/wrappers.proto";
import "fmp/extensions.proto";

// ElementType enumerates the types of network elements that can
// be associated with tags.
enum ElementType {
	// ELEMENT_TYPE_UNSPECIFIED is the default value.
	ELEMENT_TYPE_UNSPECIFIED = 0;
	// ELEMENT_TYPE_DEVICE is used for device tags.
	ELEMENT_TYPE_DEVICE = 1;
	// ELEMENT_TYPE_INTERFACE is used for interface tags.
	ELEMENT_TYPE_INTERFACE = 2;
	// ELEMENT_TYPE_VIRTUAL is used for virtual entities(applications/services) tags.
	ELEMENT_TYPE_VIRTUAL = 3;
}

// ElementSubType enumerates the sub-types of network elements that can
// be associated with tags.
enum ElementSubType {
	// ELEMENT_SUB_TYPE_UNSPECIFIED is the default value.
	ELEMENT_SUB_TYPE_UNSPECIFIED = 0;
	// ELEMENT_SUB_TYPE_DEVICE is used for EOS or
	// third-party devices discovered via LLDP/SNMP.
	ELEMENT_SUB_TYPE_DEVICE = 1;
	// ELEMENT_SUB_TYPE_VDS is used for VMWare vSphere Distributed Switch (VDS) tags.
	ELEMENT_SUB_TYPE_VDS = 2;
	// ELEMENT_SUB_TYPE_WORKLOAD_SERVER is used for workload server
	// tags (such as VMWare ESXi host).
	// A workload server is a server/data storage device on which
	// the hypervisor is installed.
	ELEMENT_SUB_TYPE_WORKLOAD_SERVER = 3;
	// ELEMENT_SUB_TYPE_VM is used for VM tags.
	// A VM is a software computer that, like a physical computer,
	// runs an operating system and applications.
	ELEMENT_SUB_TYPE_VM = 4;
	// ELEMENT_SUB_TYPE_APPLICATION is used for application tags.
	// An application is defined as a set of services where each service provides
	// a subset of the application’s functionality. An application can exist without
	// a service but not vice-versa.
	ELEMENT_SUB_TYPE_APPLICATION = 5;
}

// TagKey uniquely identifies a tag.
message TagKey {
	option (fmp.model_key) = true;
	// workspace_id is the ID of a workspace. The special ID ""
	// identifies the location where merged tags reside.
	google.protobuf.StringValue workspace_id = 1;
	// element_type is the category of network element to which
	// this tag can be assigned.
	ElementType element_type = 2;
	// label is an arbitrary label.
	google.protobuf.StringValue label = 3;
	// value is an arbitrary value.
	google.protobuf.StringValue value = 4;
	// element_sub_type is the sub-category of network element
	// to which this tag can be assigned.
	ElementSubType element_sub_type = 5;
}

// TagConfig holds a configuration for a user tag.
// The tags that belong to entities other than ELEMENT_SUB_TYPE_DEVICE
// will always be present in mainline only.
message TagConfig {
	option (fmp.model) = "rw";
	// key identifies a tag. The special workspace ID "" for
	// merged tags should not be set here.
	TagKey key = 1;
	// remove indicates whether to remove (true) or add (false,
	// unset) the tag identified by the key if the encompassing
	// workspace merges.
	google.protobuf.BoolValue remove = 2;
}

// CreatorType enumerates the types of entities that can create
// a tag.
enum CreatorType {
	// CREATOR_TYPE_UNSPECIFIED is the default value.
	CREATOR_TYPE_UNSPECIFIED = 0;
	// CREATOR_TYPE_SYSTEM is used for system tags.
	CREATOR_TYPE_SYSTEM = 1;
	// CREATOR_TYPE_USER is used for user tags.
	CREATOR_TYPE_USER = 2;
	// CREATOR_TYPE_EXTERNAL is used for tags created from external sources.
	// For E.g., vCenter
	CREATOR_TYPE_EXTERNAL = 3;
}

// Tag holds a merge-preview or the existing merged state (if the
// workspace ID is "") of a tag.
message Tag {
	option (fmp.model) = "ro";
	// key identifies a tag.
	TagKey key = 1;
	// creator_type is the creator type of the tag.
	CreatorType creator_type = 2;
	// assigned indicates whether the tag is assigned
	// (true) or not (false).
	google.protobuf.BoolValue assigned = 3;
}

// TagAssignmentKey uniquely identifies an assignment between
// a tag and a network element.
message TagAssignmentKey {
	option (fmp.model_key) = true;
	// workspace_id is the ID of a workspace. The special ID ""
	// identifies the location where merged assignments reside.
	google.protobuf.StringValue workspace_id = 1;
	// element_type is the element type of a tag. What should
	// be set per element type:
	//
	// ELEMENT_TYPE_DEVICE: device_id
	// ELEMENT_TYPE_INTERFACE: device_id, interface_id
	// ELEMENT_TYPE_VIRTUAL:
	//		primary_entity_id -> application_id
	//		secondary_entity_id -> service_id
	ElementType element_type = 2;
	// label is the label of a tag.
	google.protobuf.StringValue label = 3;
	// value is the value of a tag.
	google.protobuf.StringValue value = 4;
	// device_id identifies a device.
	google.protobuf.StringValue device_id = 5;
	// interface_id identifies an interface on a device.
	google.protobuf.StringValue interface_id = 6;
	// element_sub_type is the element sub-type of a tag.
	ElementSubType element_sub_type = 7;
	// primary_entity_id holds unique identifiers of an application/device. 
	// The primary entity is the entity which can exist by itself or can be 
	// associated with a secondary entity.
	google.protobuf.StringValue primary_entity_id = 8;
	// secondary_entity_id holds unique identifier of a service/interface. The secondary 
	// entity is the entity which cannot exist by itself and always has to be associated 
	// with a primary entity.
	google.protobuf.StringValue secondary_entity_id = 9;
}

// TagAssignmentConfig holds a configuration for an assignment
// between a tag and a network element.
// The tag assignments that belong to entities other than ELEMENT_SUB_TYPE_DEVICE
// will always be present in mainline only.
message TagAssignmentConfig {
	option (fmp.model) = "rw";
	// key identifies an assignment. The special workspace ID ""
	// for merged assignments should not be set here.
	TagAssignmentKey key = 1;
	// remove indicates whether to remove (true) or add (false,
	// unset) the assignment identified by the key if the
	// encompassing workspace merges.
	google.protobuf.BoolValue remove = 2;
}

// TagAssignment holds a merge-preview or the existing merged
// state (if the workspace ID is "") of an assignment between
// a tag and a network element.
message TagAssignment {
	option (fmp.model) = "ro";
	// key identifies an assignment.
	TagAssignmentKey key = 1;
	// tag_creator_type is the creator type of the tag
	// involved in the assignment.
	CreatorType tag_creator_type = 2;
}

// ElementFilter is a custom filter for elements.
message ElementFilter {
	// search can be used to search for elements via a tag query.
	ElementSearchFilter search = 1;
}

// ElementSearchFilter is a filter that can be used to search for a set of
// elements using a tag query.
message ElementSearchFilter {
	// query_element_type (required) indicates the type of element against which
	// the query will be executed. To search by sub-type, use the special "type:"
	// tag from within the query.
	ElementType query_element_type = 1;
	// query (required) is a tag query. This is a string that specifies a set of
	// tag assignment conditions. For example:
	//
	// - "Campus:SF"
	//     Match any device that has the "Campus:SF" tag assigned to it.
	//     I.e., match any device in the SF campus.
	// - "Campus:*"
	//     Match any device that has any "Campus:" tag assigned to it.
	//     I.e., match any device in any campus.
	// - "Campus:SF AND Role:Spine"
	//     Match any device that has the "Campus:SF" and "Role:Spine"
	//     tag assigned to it.
	//     I.e., match any spine device in the SF campus.
	//
	// TODO: Link to grammar file.
	google.protobuf.StringValue query = 2;
	// workspace_id is the ID of a workspace. If set, it indicates that the
	// search space should be constrained only to the elements that are known
	// or configured in the given workspace.
	google.protobuf.StringValue workspace_id = 10;
	// exclude_unregistered_elements indicates whether elements that are not registered
	// in the Inventory and Topology (I&T) Studio should be excluded from the results.
	google.protobuf.BoolValue exclude_unregistered_elements = 11;
	// ignore_topology_tags indicates whether topology_hint tags should be ignored during
	// the execution of the query.
	google.protobuf.BoolValue ignore_topology_tags = 12;
}

// ElementKey uniquely identifies a tagged or untagged network element.
message ElementKey {
	option (fmp.model_key) = true;
	// type is the type of the element.
	ElementType type = 1;
	// sub_type is the sub-type of the element.
	ElementSubType sub_type = 2;
	// primary_id is the device ID of the element. The value of
	// this ID is based on type and sub_type:
	//
	// type: DEVICE
	//   sub_type: DEVICE
	//     id: <serial_number>
	//   sub_type: VDS, WORKLOAD_SERVER, VM
	//     id: <uuid>
	// type: INTERFACE
	//   sub_type: DEVICE
	//     id: <serial_number>
	//   sub_type: VDS, WORKLOAD_SERVER, VM
	//     id: <uuid>
	// type: VIRTUAL
	//   sub_type: APPLICATION
	//     id: <application_id>
	google.protobuf.StringValue primary_id = 3;
	// secondary_id is the interface ID of the element. The value of
	// this ID is based on type and sub_type:
	//
	// type: DEVICE
	//   N/A
	// type: INTERFACE
	//   sub_type: DEVICE
	//     id: <interface_name>
	//   sub_type: VDS, WORKLOAD_SERVER, VM
	//     id: <interface_name>
	// type: VIRTUAL
	//   sub_type: APPLICATION
	//     id: <service_id>
	google.protobuf.StringValue secondary_id = 4;
}

// Element holds basic information about a tagged or untagged network
// element.
message Element {
	option (fmp.model) = "ro";
	option (fmp.custom_filter) = "ElementFilter";
	// key uniquely identifies the element.
	ElementKey key = 1;
}
