import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'CloudVision APIs',
      link: {
        type: 'doc',
        id: 'index',
      },
      items: [
        {
          type: 'category',
          label: 'Modeling',
          link: {
            type: 'doc',
            id: 'modeling/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'Uniform RPCs',
          link: {
            type: 'doc',
            id: 'rpcs/index',
          },
          items: [
            {
              type: 'doc',
              id: 'rpcs/errors',
              label: 'Error Handling',
              className: 'highlight-item',
            },
            {
              type: 'doc',
              id: 'rpcs/filtering',
              label: 'Filtering',
              className: 'highlight-item',
            },
            'rpcs/getone',
            'rpcs/getsome',
            'rpcs/getall',
            'rpcs/subscribe',
            'rpcs/set',
            'rpcs/setsome',
            'rpcs/delete',
            'rpcs/deletesome',
          ],
        },
        {
          type: 'category',
          label: 'Connecting',
          link: {
            type: 'doc',
            id: 'connecting/index',
          },
          items: [],
        },
        {
          type: 'category',
          label: 'Clients',
          link: {
            type: 'doc',
            id: 'clients/index',
          },
          items: [
            'clients/existing',
            'clients/creating',
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          link: {
            type: 'doc',
            id: 'examples/index',
          },
          items: [
            {
              type: 'category',
              label: 'gRPC',
              link: {
                type: 'doc',
                id: 'examples/gRPC/index',
              },
              items: [],
            },
            {
              type: 'category',
              label: 'REST API Examples',
              link: {
                type: 'doc',
                id: 'examples/REST/index',
              },
              items: [
                {
                  type: 'doc',
                  label: 'Bug Exposure',
                  id: 'examples/REST/bugexposure/index',
                },
                {
                  type: 'doc',
                  label: 'Change Control',
                  id: 'examples/REST/changecontrol/index',
                },
                {
                  type: 'doc',
                  label: 'Dashboard',
                  id: 'examples/REST/dashboard/index',
                },
                {
                  type: 'doc',
                  label: 'Endpoint Location',
                  id: 'examples/REST/endpointlocation/index',
                },
                {
                  type: 'doc',
                  label: 'Events',
                  id: 'examples/REST/events/index',
                },
                {
                  type: 'doc',
                  label: 'Inventory',
                  id: 'examples/REST/inventory/index',
                },
                {
                  type: 'doc',
                  label: 'Lifecycle',
                  id: 'examples/REST/lifecycle/index',
                },
                {
                  type: 'doc',
                  label: 'Studios and Workspaces',
                  id: 'examples/REST/studios and workspaces/index',
                },
                {
                  type: 'doc',
                  label: 'Tags',
                  id: 'examples/REST/tag/index',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Models',
          link: {
            type: 'doc',
            id: 'models',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'models',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
